### ISSUE TITLE
The idea of tool is very good, but I failed in win7 test.

### ISSUE THREAD

**Issue by mygit2014** [C-Sto/goWMIExec#1]
The idea of tool is very good, but I failed in win7 test.

![image](https://user-images.githubusercontent.com/5819987/67556747-4b9f1900-f746-11e9-9430-0729a811b112.png)

![image](https://user-images.githubusercontent.com/5819987/67556852-7f7a3e80-f746-11e9-9d20-295411ec95a9.png)

**Comment by C-Sto** [comment]
Hmm, that is not an error I'd expect to see. I'm in the process of refactoring the code a bit - I'll keep this issue open until I can confirm it works on Win7, though I can't see why it wouldn't already. Would you be willing to provide a pcap of the traffic? just port 135, and the rpc negotiated port

**Comment by C-Sto** [comment]
Hey - I wasn't able to reproduce the error, but the most recent few commits should have resolved some of the more blatant issues which I suspect might be related. Can you try again and let me know if you still get the same errors?

**Comment by C-Sto** [comment]
Closing, since major changes since the issue was opened and I'm pretty confident that issue has been fixed
