### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by andrewpedia** [C-Sto/goWMIExec#2]
1.599615871744067e+09   info    wmiexec/wmiexec.go:68   Hostname too long (over 16 chars). Using first 15 chars: APPLEDEMACBOOK-
1.599615871774055e+09   info    wmiexec/wmiexec.go:176  Successfully connected to host and sent an RPC request packet
1.5996158717741098e+09  info    wmiexec/wmiexec.go:188  Resolved names, all network string bindings for host:
1.599615871774127e+09   info    wmiexec/wmiexec.go:197          vagrant-pc
1.5996158717741382e+09  info    wmiexec/wmiexec.go:197          192.168.3.120
1.59961587177415e+09    info    wmiexec/wmiexec.go:205  Using first value as target hostname: vagrant-pc
1.599615871833118e+09   info    wmiexec/wmiexec.go:299  WMI Access possible!
panic: runtime error: slice bounds out of range [:33] with capacity

**Comment by C-Sto** [comment]
Hrm, I'm not sure this is the full error output - occasionally it will fail for no apparent reason, and then work if you run it again (which indicates that there might be a race/timing issue somewhere, and fills me with dread). Are you able to reproduce the error consistently?

**Comment by andrewpedia** [comment]
how to get the needed hash?
